### PR TITLE
added missing lib call for ckeditor

### PR DESCRIPTION
**Pull request by Rubemlrm**
added ckeditor call so ckeditor can load on specified form elements

### CODE REVIEW

**Comment by butschster** [comment]
Can you show me an example?

**Comment by Rubemlrm** [comment]
For instance when i add this to a form : 

>AdminFormElement::ckeditor('presentation_pt', 'Apresentação PT:'),

If i dont have that lib on Meta::loadPackage call i only get textarea without ckeditor working on them.

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.22.96-beta

**Comment by butschster** [comment]
Hi, have you any questions?

**Pull request closed without merging**
